include:
  - local: .gitlab-ci/deploy.gitlab-ci.yml

.envrironment-template: &environment-template
  name: staging
  url: http://staging.example.domain # TODO: Set your value!

.template:
  extends: .raw:template
  only:
    - tags
  environment:
    <<: *environment-template
    on_stop: stop-environment
  tags:
    - server-tag # TODO: Set your value!

stop-environment:
  extends: .template
  stage: stopping
  when: manual
  needs: []
  environment:
    <<: *environment-template
    action: stop
  script: docker-compose stop
