version: '3.7'
x-user: &user
  user: "${UID}:${GID}"
services:
  postgres:
    ports:
      - published: 5432
        target: 5432
  rabbitmq:
    ports:
      - published: 15672
        target: 15672
      - published: 5672
        target: 5672
  web-service:
    <<: *user
    ports:
      - published: 80
        target: 8080
  auth-service:
    <<: *user
    build:
      args:
        DEBUG: "${DEBUG:-false}"
  core-service:
    <<: *user
    build:
      args:
        DEBUG: "${DEBUG:-false}"
  notification-service:
    <<: *user
    build:
      args:
        DEBUG: "${DEBUG:-false}"
