version: '3.7'
services:
  postgres:
    ports:
      - published: 5432
        target: 5432
  rabbitmq:
    image: ${RABBITMQ_IMAGE:-egalbox/rabbitmq:2.0.1}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - published: 15672
        target: 15672
      - published: 5672
        target: 5672
  web-service:
    ports:
      - published: 80
        target: 8080
  auth-service:
    build:
      args:
        DEBUG: 'true'
    user: ${UID}:${GID}
    volumes:
      - ../templates/server/auth-service:/app:rw
  core-service:
    build:
      args:
        DEBUG: 'true'
    user: ${UID}:${GID}
    volumes:
      - ./server/core-service:/app:rw
