version: '3.7'
services:
  postgres:
    ports:
      - published: 5432
        target: 5432
  rabbitmq:
    ports:
      - published: 15672
        target: 15672
      - published: 5672
        target: 5672
  web-service:
    ports:
      - published: 80
        target: 8080
  auth-service:
    build:
      args:
        DEBUG: "${DEBUG:-false}"
    user: ${UID}:${GID}
  core-service:
    build:
      args:
        DEBUG: "${DEBUG:-false}"
    user: ${UID}:${GID}
  notification-service:
    build:
      args:
        DEBUG: "${DEBUG:-false}"
    user: ${UID}:${GID}
