version: "3.7"
services:
  node:
    image: node:16
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run watch"
    healthcheck:
      test: [ "CMD-SHELL", "[ ! -d ./dist/cjs -o ! -d ./dist/esm ] && exit 1" ]
      start_period: 360s
      interval: 3s
      timeout: 3s
      retries: 8
