name: Build release

on:
  release:
    types:
      - published

jobs:

  package-php-laravel-event-bus:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y tree
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            git-filter-repo
      # p.s. Main info from https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository
      # TODO: git_branch auto set.
      - name: Split
        run: |
          git_branch='4.x'
          split_dir=packages/php-laravel-event-bus
          split_remote='https://rollsover:${{ secrets.ACCESS_TOKEN }}@github.com/egal/php-laravel-event-bus-package.git'
          git clone https://rollsover:${{ secrets.ACCESS_TOKEN }}@github.com/egal/framework.git .
          git filter-repo --subdirectory-filter ${split_dir}/
          git remote set-url origin ${split_remote} || git remote add origin ${split_remote}
          git push -u origin ${git_branch}
          git push -u origin ${{ github.event.release.tag_name }}

  package-npm-refine-keycloak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./packages/npm-refine-keycloak && \
            npm install && \
            npm version ${{ github.event.release.tag_name }} && \
            npm run build && \
            npm publish --access public

  package-npm-refine-laravel-orion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./packages/npm-refine-laravel-orion && \
            npm install && \
            npm version ${{ github.event.release.tag_name }} && \
            npm run build && \
            npm publish --access public

  notify:
    if: "!github.event.release.prerelease"
    needs:
      - package-npm-refine-keycloak
      - package-npm-refine-laravel-orion
    runs-on: ubuntu-latest
    steps:
      - uses: egal/release-notify-action@main
        with:
          repository_name: ${{ github.repository }}
          release_json: ${{ toJson(github.event.release) }}
          telegram_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID_FOR_RELEASE_NOTIFY }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
